name: abastecimento_app
description: "Aplicativo de controle de abastecimento e veículos."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.10.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Firebase atualizado e compatível
  firebase_core: ^3.1.1
  firebase_auth: ^5.1.1
  cloud_firestore: ^5.1.1

  # Ícones padrão
  cupertino_icons: ^1.0.8

  # Gerenciamento de estado recomendado pela atividade
  provider: ^6.1.2

  # Gráficos (para o bônus)
  fl_chart: ^0.69.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
